### ISSUE TITLE
How can I use events?

### ISSUE THREAD

**Issue by andreich1980** [vue-bulma/datepicker#51]
I'm reading docs at https://chmln.github.io/flatpickr/events/ but can't figure out how to manage events.

I tried this
```
<template>
    <datepicker :config="options" v-on:on-open="myMethod"></datepicker>
</template>
```
and this
```
<template>
    <datepicker :config="options" v-on:onOpen="myMethod"></datepicker>
</template>
```
and this
```
<template>
    <datepicker :config="options" @onOpen="myMethod"></datepicker>
</template>
```
Nothing happens :(

What am I missing?

**Comment by andreich1980** [comment]
Found event `@input` with Vue browser extension.
But when I want to select range it fires twice.
Any suggestions?

**Comment by luventa** [comment]
This component will only emit event `input` for now.
Range selection will definitely fires `input` twice because the `selectedDates` changes twice...

Other events that belongs to Flatpickr can be set inside `config`
For example, config like this will works

```vue
<datepicker v-model="dateRange" 
  :config="{ mode: 'range', onOpen: this.onRangeOpen }">
</datepicker>

export default {
 methods: {
   onRangeOpen () {
     console.log('test')
   }
 }
}
```

Here is the [events doc](https://chmln.github.io/flatpickr/events/) for Flatpickr.
Event `onValueUpdate` is not available because this component is using it. Other events can be configured as the example above.
